gmail_to_pdf:
  save_attachments: false
  texts:
    date_prefix: "Document generated on"
    document_title: "Gmail correspondence exported to PDF"
    footer: "Gmail to PDF | Marek Stachura (@marekstachura)"
  criteria:
    1:
      from: "alice@gmail.com"
      before: "2014-01-01"
      after: "2013-05-31"
    2:
      to: "bob@gmail.com"
      after: "2013-05-31"